baseURL = "https://transcriptionproject.github.io/blog/"
disablePathToLower = true
languageCode = "en-us"
title = "Zain Rizvi"
theme = "hugo-theme-cleanwhite"
relativeURLs = true
canonifyURLs = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  custom_css = ["css/custom.css"]
  header_image = "https://www.zainrizvi.io/content/images/2020/07/larisa-birta-77vhoasr6-c-unsplash.jpg"
  slogan = "Interested in software engineering, business, or psychology? You're in the right place"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 2
  [[menu.main]]
    name = "Newsletter"
    url = "/newsletter/"
    weight = 3