baseURL = "https://transcriptionproject.github.io/blog/"
disablePathToLower = true
languageCode = "en-us"
title = "Zain Rizvi"
theme = "hugo-theme-cleanwhite"
relativeURLs = true
canonifyURLs = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  custom_css = ["css/custom.css"]
