name: Deploy Hugo site to GitHub Pages

on:
  push:
    branches:
      - main

# Add this permissions block
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: false  # Don't try to get submodules
          fetch-depth: 0    # Fetch all history

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true
          
      - name: Clone theme
        run: |
          mkdir -p site/themes
          git clone https://github.com/zhaohuabing/hugo-theme-cleanwhite.git site/themes/hugo-theme-cleanwhite

      - name: Build
        run: cd site && hugo --minify  # Change to site directory first

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site/public  # Publish from the site/public directory